# Generated by Django 4.2.7 on 2025-10-01 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('team', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('on_call', 'On Call'), ('break', 'On Break'), ('offline', 'Offline'), ('training', 'Training')], default='offline', max_length=20)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('specializations', models.JSONField(blank=True, default=list)),
                ('total_calls', models.IntegerField(default=0)),
                ('successful_calls', models.IntegerField(default=0)),
                ('average_call_duration', models.FloatField(default=0.0)),
                ('customer_satisfaction', models.FloatField(default=0.0)),
                ('use_ai_assistance', models.BooleanField(default=True)),
                ('ai_confidence_threshold', models.FloatField(default=0.8)),
                ('preferred_ai_model', models.CharField(default='homeai-standard', max_length=50)),
                ('twilio_worker_sid', models.CharField(blank=True, max_length=100)),
                ('extension_number', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('hired_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HomeAIIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key', models.CharField(blank=True, max_length=200)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('auto_suggestions', models.BooleanField(default=True)),
                ('real_time_assistance', models.BooleanField(default=True)),
                ('sentiment_analysis', models.BooleanField(default=True)),
                ('call_summarization', models.BooleanField(default=True)),
                ('total_requests', models.IntegerField(default=0)),
                ('successful_requests', models.IntegerField(default=0)),
                ('last_request_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_integrations', to='agents.agent')),
            ],
        ),
        migrations.CreateModel(
            name='AgentSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('communication', 'Communication'), ('sales', 'Sales'), ('support', 'Support'), ('language', 'Language'), ('product', 'Product Knowledge')], max_length=20)),
                ('proficiency_level', models.IntegerField(default=1)),
                ('is_certified', models.BooleanField(default=False)),
                ('certification_date', models.DateField(blank=True, null=True)),
                ('certification_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='agents.agent')),
            ],
        ),
        migrations.CreateModel(
            name='AgentShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift_type', models.CharField(choices=[('regular', 'Regular'), ('overtime', 'Overtime'), ('holiday', 'Holiday'), ('weekend', 'Weekend')], default='regular', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('total_break_time', models.IntegerField(default=0)),
                ('calls_handled', models.IntegerField(default=0)),
                ('avg_handle_time', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='agents.agent')),
            ],
        ),
        migrations.CreateModel(
            name='AgentPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_calls', models.IntegerField(default=0)),
                ('answered_calls', models.IntegerField(default=0)),
                ('completed_calls', models.IntegerField(default=0)),
                ('average_talk_time', models.FloatField(default=0.0)),
                ('average_hold_time', models.FloatField(default=0.0)),
                ('customer_satisfaction', models.FloatField(default=0.0)),
                ('first_call_resolution', models.IntegerField(default=0)),
                ('escalations', models.IntegerField(default=0)),
                ('ai_suggestions_used', models.IntegerField(default=0)),
                ('ai_accuracy_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='agents.agent')),
            ],
            options={
                'unique_together': {('agent', 'date')},
            },
        ),
    ]
