# Generated by Django 4.2.7 on 2025-10-01 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Agent ka naam', max_length=100)),
                ('personality_type', models.CharField(choices=[('friendly', 'Friendly & Casual'), ('professional', 'Professional & Formal'), ('persuasive', 'Sales Focused'), ('supportive', 'Customer Support'), ('custom', 'Custom Trained')], default='friendly', max_length=20)),
                ('voice_model', models.CharField(default='en-US-female-1', max_length=50)),
                ('status', models.CharField(choices=[('training', 'Initial Training'), ('learning', 'Learning from Calls'), ('active', 'Fully Active'), ('optimizing', 'Performance Optimizing'), ('paused', 'Paused')], default='training', max_length=20)),
                ('training_level', models.IntegerField(default=0, help_text='0-100 training completion')),
                ('calls_handled', models.IntegerField(default=0)),
                ('successful_conversions', models.IntegerField(default=0)),
                ('conversation_memory', models.JSONField(default=dict, help_text='Agent ki memory aur learning')),
                ('customer_preferences', models.JSONField(default=dict, help_text='Customer behavior patterns')),
                ('sales_script', models.TextField(blank=True, help_text='Dynamic sales script')),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('avg_call_duration', models.FloatField(default=0.0)),
                ('customer_satisfaction', models.FloatField(default=0.0)),
                ('working_hours_start', models.TimeField(default='09:00')),
                ('working_hours_end', models.TimeField(default='18:00')),
                ('max_daily_calls', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Agent',
                'verbose_name_plural': 'AI Agents',
                'db_table': 'ai_agents',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('interest_level', models.CharField(choices=[('cold', 'Not Interested'), ('warm', 'Somewhat Interested'), ('hot', 'Very Interested'), ('converted', 'Purchased')], default='warm', max_length=20)),
                ('call_preference_time', models.CharField(choices=[('morning', 'Morning (9-12)'), ('afternoon', 'Afternoon (12-17)'), ('evening', 'Evening (17-20)'), ('anytime', 'Anytime')], default='anytime', max_length=20)),
                ('communication_style', models.CharField(blank=True, help_text='Formal, casual, etc', max_length=50)),
                ('total_calls', models.IntegerField(default=0)),
                ('successful_calls', models.IntegerField(default=0)),
                ('last_interaction', models.DateTimeField(blank=True, null=True)),
                ('next_followup', models.DateTimeField(blank=True, null=True)),
                ('conversation_notes', models.JSONField(default=dict)),
                ('preferences', models.JSONField(default=dict, help_text='Customer ki pasand, requirements')),
                ('objections', models.JSONField(default=list, help_text='Customer ke objections aur responses')),
                ('is_do_not_call', models.BooleanField(default=False)),
                ('is_converted', models.BooleanField(default=False)),
                ('conversion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profiles', to='agents.aiagent')),
            ],
            options={
                'db_table': 'customer_profiles',
                'unique_together': {('ai_agent', 'phone_number')},
            },
        ),
        migrations.CreateModel(
            name='ScheduledCallback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_datetime', models.DateTimeField()),
                ('reason', models.CharField(help_text='Callback ka reason', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rescheduled_from', models.DateTimeField(blank=True, null=True)),
                ('priority_level', models.IntegerField(default=1, help_text='1-5 priority')),
                ('expected_outcome', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_callbacks', to='agents.aiagent')),
                ('customer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.customerprofile')),
            ],
            options={
                'db_table': 'scheduled_callbacks',
                'ordering': ['scheduled_datetime'],
            },
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_type', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('scheduled', 'Scheduled Callback'), ('followup', 'Follow-up')], max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('outcome', models.CharField(choices=[('answered', 'Call Answered'), ('no_answer', 'No Answer'), ('busy', 'Line Busy'), ('interested', 'Customer Interested'), ('callback_requested', 'Callback Requested'), ('not_interested', 'Not Interested'), ('converted', 'Sale Completed')], max_length=30)),
                ('customer_response', models.TextField(blank=True)),
                ('agent_notes', models.TextField(blank=True)),
                ('conversation_transcript', models.TextField(blank=True)),
                ('sentiment_analysis', models.JSONField(default=dict)),
                ('extracted_insights', models.JSONField(default=dict)),
                ('followup_scheduled', models.BooleanField(default=False)),
                ('followup_datetime', models.DateTimeField(blank=True, null=True)),
                ('followup_reason', models.CharField(blank=True, max_length=200)),
                ('twilio_call_sid', models.CharField(blank=True, max_length=100)),
                ('recording_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='agents.aiagent')),
                ('customer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='agents.customerprofile')),
            ],
            options={
                'db_table': 'ai_call_sessions',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAgentTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('training_type', models.CharField(choices=[('initial', 'Initial Setup Training'), ('script', 'Sales Script Training'), ('objection_handling', 'Objection Handling'), ('product_knowledge', 'Product Knowledge'), ('real_time', 'Real-time Learning')], max_length=30)),
                ('training_data', models.JSONField(help_text='Training content and scripts')),
                ('completion_percentage', models.IntegerField(default=0)),
                ('client_instructions', models.TextField(blank=True, help_text='Client ke instructions')),
                ('sales_goals', models.JSONField(default=dict, help_text='Sales targets aur goals')),
                ('product_info', models.JSONField(default=dict, help_text='Product/service details')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='agents.aiagent')),
            ],
            options={
                'db_table': 'ai_agent_training',
            },
        ),
    ]
