# Generated by Django 4.2.7 on 2025-10-03 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0002_aiagent_customerprofile_scheduledcallback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('schedule_type', models.CharField(choices=[('immediate', 'Start Immediately'), ('scheduled', 'Schedule for Later')], default='immediate', max_length=20)),
                ('scheduled_datetime', models.DateTimeField(blank=True, null=True)),
                ('total_contacts', models.IntegerField(default=0)),
                ('contacts_called', models.IntegerField(default=0)),
                ('successful_calls', models.IntegerField(default=0)),
                ('failed_calls', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('max_attempts_per_contact', models.IntegerField(default=3)),
                ('retry_interval_hours', models.IntegerField(default=24)),
                ('preferred_call_time_start', models.TimeField(blank=True, null=True)),
                ('preferred_call_time_end', models.TimeField(blank=True, null=True)),
                ('assigned_agent_ai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.aiagent')),
                ('assigned_agent_human', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessKnowledge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_description', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('products_services', models.JSONField(blank=True, default=list)),
                ('pricing_information', models.JSONField(blank=True, default=dict)),
                ('sales_script', models.TextField(blank=True)),
                ('common_objections', models.JSONField(blank=True, default=list)),
                ('objection_responses', models.JSONField(blank=True, default=dict)),
                ('business_hours', models.JSONField(blank=True, default=dict)),
                ('contact_information', models.JSONField(blank=True, default=dict)),
                ('knowledge_documents', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_knowledge', to='agents.aiagent')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('busy', 'Busy'), ('no_answer', 'No Answer'), ('do_not_call', 'Do Not Call')], default='pending', max_length=20)),
                ('attempts_made', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('call_duration', models.IntegerField(default=0)),
                ('call_outcome', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_contacts', to='agents.campaign')),
                ('customer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.customerprofile')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('campaign', 'customer_profile')},
            },
        ),
        migrations.CreateModel(
            name='AgentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('work_start_time', models.TimeField()),
                ('work_end_time', models.TimeField()),
                ('break_start_time', models.TimeField(blank=True, null=True)),
                ('break_end_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='agents.agent')),
            ],
            options={
                'ordering': ['day_of_week'],
                'unique_together': {('agent', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='AgentPerformanceMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_calls', models.IntegerField(default=0)),
                ('successful_calls', models.IntegerField(default=0)),
                ('failed_calls', models.IntegerField(default=0)),
                ('average_call_duration', models.FloatField(default=0.0)),
                ('customer_satisfaction_score', models.FloatField(default=0.0)),
                ('total_ratings', models.IntegerField(default=0)),
                ('total_revenue_generated', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('conversions', models.IntegerField(default=0)),
                ('active_hours', models.FloatField(default=0.0)),
                ('break_hours', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_ai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detailed_performance_metrics', to='agents.aiagent')),
                ('agent_human', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detailed_performance_metrics', to='agents.agent')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('agent_human', 'date'), ('agent_ai', 'date')},
            },
        ),
    ]
