# Generated by Django 4.2.7 on 2025-10-03 14:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_campaign_businessknowledge_campaigncontact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCallCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('campaign_type', models.CharField(choices=[('general', 'General Outreach'), ('followup', 'Follow-up Calls'), ('new_leads', 'New Leads'), ('callbacks', 'Scheduled Callbacks'), ('test', 'Test Campaign')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('target_customers', models.IntegerField(default=50)),
                ('calls_per_hour', models.IntegerField(default=10)),
                ('working_hours_start', models.CharField(default='09:00', max_length=5)),
                ('working_hours_end', models.CharField(default='17:00', max_length=5)),
                ('campaign_data', models.JSONField(default=dict)),
                ('total_contacts', models.IntegerField(default=0)),
                ('contacts_called', models.IntegerField(default=0)),
                ('successful_calls', models.IntegerField(default=0)),
                ('failed_calls', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_campaigns', to='agents.aiagent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoCampaignContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('calling', 'Currently Calling'), ('completed', 'Completed'), ('failed', 'Failed'), ('scheduled', 'Scheduled for Later')], default='pending', max_length=20)),
                ('priority', models.IntegerField(default=1)),
                ('scheduled_datetime', models.DateTimeField()),
                ('call_started_at', models.DateTimeField(blank=True, null=True)),
                ('call_completed_at', models.DateTimeField(blank=True, null=True)),
                ('call_outcome', models.CharField(blank=True, max_length=50)),
                ('call_duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('twilio_call_sid', models.CharField(blank=True, max_length=100)),
                ('attempts', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='agents.autocallcampaign')),
                ('customer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.customerprofile')),
            ],
            options={
                'ordering': ['-priority', 'scheduled_datetime'],
            },
        ),
    ]
