# Generated by Django 4.2.7 on 2025-10-01 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('action_type', models.CharField(choices=[('call', 'Make Call'), ('sms', 'Send SMS'), ('email', 'Send Email'), ('note', 'Add Note'), ('schedule', 'Schedule Callback'), ('transfer', 'Transfer Call')], max_length=20)),
                ('icon', models.CharField(default='phone', max_length=50)),
                ('color', models.CharField(default='primary', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_type', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('answered', 'Answered'), ('completed', 'Completed'), ('failed', 'Failed'), ('busy', 'Busy'), ('no_answer', 'No Answer'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('caller_number', models.CharField(max_length=20)),
                ('callee_number', models.CharField(max_length=20)),
                ('caller_name', models.CharField(blank=True, max_length=100)),
                ('twilio_call_sid', models.CharField(blank=True, max_length=100)),
                ('twilio_conference_sid', models.CharField(blank=True, max_length=100)),
                ('twilio_recording_url', models.URLField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_sentiment', models.CharField(blank=True, max_length=20)),
                ('ai_keywords', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CallScript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('script_type', models.CharField(choices=[('greeting', 'Greeting'), ('sales', 'Sales'), ('support', 'Support'), ('survey', 'Survey'), ('followup', 'Follow-up')], max_length=20)),
                ('content', models.TextField()),
                ('use_ai_assistance', models.BooleanField(default=False)),
                ('ai_prompts', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recording_url', models.URLField()),
                ('duration', models.IntegerField(default=0)),
                ('file_size', models.BigIntegerField(default=0)),
                ('transcription', models.TextField(blank=True)),
                ('transcription_confidence', models.FloatField(default=0.0)),
                ('sentiment_analysis', models.JSONField(blank=True, default=dict)),
                ('key_phrases', models.JSONField(blank=True, default=list)),
                ('compliance_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='calls.callsession')),
            ],
        ),
        migrations.CreateModel(
            name='CallQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='waiting', max_length=20)),
                ('priority', models.IntegerField(default=1)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('wait_time', models.IntegerField(default=0)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
                ('call_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calls.callsession')),
            ],
        ),
    ]
