# Generated by Django 5.2.7 on 2025-10-08 12:30

import agents.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Agent name', max_length=100)),
                ('agent_type', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', help_text='Agent type: Inbound or Outbound', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', help_text='Agent status: Active or Paused', max_length=20)),
                ('calls_handled', models.IntegerField(default=0, help_text='Total calls handled by agent')),
                ('total_calls', models.IntegerField(default=0)),
                ('successful_calls', models.IntegerField(default=0)),
                ('average_call_duration', models.FloatField(default=0.0)),
                ('customer_satisfaction', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('hume_ai_api_key', models.CharField(blank=True, help_text='Hume AI API key for this agent', max_length=200)),
                ('hume_ai_config', models.JSONField(default=dict, help_text='Hume AI configuration settings')),
                ('voice_model', models.CharField(default='en-US-female-1', help_text='Selected voice model', max_length=50)),
                ('tone_settings', models.JSONField(default=dict, help_text='Voice tone and personality settings')),
                ('operating_hours', models.JSONField(default=dict, help_text='Time windows when agent is operational')),
                ('auto_answer_enabled', models.BooleanField(default=False, help_text='Enable auto-answer for inbound calls')),
                ('sales_script_file', models.FileField(blank=True, help_text='Upload sales script/template file', null=True, upload_to=agents.models.agent_script_upload_path)),
                ('sales_script_text', models.TextField(blank=True, help_text='Sales script text content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('human_operator', models.OneToOneField(blank=True, help_text='Human operator for this agent (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_agent', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='User who owns/created this agent', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BusinessKnowledge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('website_url', models.URLField(blank=True, help_text='Business website URL')),
                ('knowledge_file', models.FileField(blank=True, help_text='Upload business knowledge file (PDF, DOCX, TXT)', null=True, upload_to=agents.models.business_knowledge_upload_path)),
                ('file_type', models.CharField(blank=True, choices=[('pdf', 'PDF Document'), ('docx', 'Word Document'), ('txt', 'Text File'), ('csv', 'CSV File')], max_length=10)),
                ('knowledge_text', models.TextField(blank=True, help_text='Business knowledge text content')),
                ('title', models.CharField(help_text='Knowledge item title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of this knowledge item')),
                ('is_processed', models.BooleanField(default=False, help_text='Whether the knowledge has been processed by AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_knowledge', to='agents.agent')),
            ],
            options={
                'verbose_name': 'Business Knowledge',
                'verbose_name_plural': 'Business Knowledge Items',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('schedule_type', models.CharField(choices=[('immediate', 'Start Immediately'), ('scheduled', 'Schedule for Later')], default='immediate', max_length=20)),
                ('scheduled_start', models.DateTimeField(blank=True, help_text='Scheduled start date/time', null=True)),
                ('total_contacts', models.IntegerField(default=0)),
                ('contacts_called', models.IntegerField(default=0)),
                ('successful_calls', models.IntegerField(default=0)),
                ('failed_calls', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='agents.agent')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('preferred_call_time', models.CharField(blank=True, help_text='Preferred time to call (from CSV upload)', max_length=100)),
                ('call_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('callback_scheduled', 'Callback Scheduled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('call_attempts', models.IntegerField(default=0)),
                ('last_call_attempt', models.DateTimeField(blank=True, null=True)),
                ('next_call_scheduled', models.DateTimeField(blank=True, null=True)),
                ('call_outcome', models.CharField(blank=True, max_length=200)),
                ('conversion_achieved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='agents.agent')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'unique_together': {('agent', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='CallQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('queue_position', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], default='pending', max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('call_duration', models.FloatField(default=0.0)),
                ('call_outcome', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_queue', to='agents.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='agents.contact')),
            ],
            options={
                'verbose_name': 'Call Queue Entry',
                'verbose_name_plural': 'Call Queue Entries',
                'ordering': ['queue_position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contacts_file', models.FileField(help_text='Upload CSV file with contacts (Name, Phone, Email, Notes, Preferred Time)', upload_to=agents.models.contacts_upload_path)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_status', models.TextField(blank=True)),
                ('contacts_imported', models.IntegerField(default=0)),
                ('errors_encountered', models.JSONField(default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_uploads', to='agents.agent')),
            ],
            options={
                'verbose_name': 'Contact Upload',
                'verbose_name_plural': 'Contact Uploads',
            },
        ),
        migrations.CreateModel(
            name='AgentPerformanceMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('calls_made', models.IntegerField(default=0)),
                ('calls_answered', models.IntegerField(default=0)),
                ('calls_completed', models.IntegerField(default=0)),
                ('calls_failed', models.IntegerField(default=0)),
                ('total_talk_time', models.FloatField(default=0.0)),
                ('average_call_duration', models.FloatField(default=0.0)),
                ('customer_satisfaction_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('first_call_resolution', models.IntegerField(default=0)),
                ('escalations', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('conversion_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ai_confidence_avg', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='agents.agent')),
            ],
            options={
                'verbose_name': 'Agent Performance Metrics',
                'verbose_name_plural': 'Agent Performance Metrics',
                'unique_together': {('agent', 'date')},
            },
        ),
    ]
