# Generated by Django 5.2.7 on 2025-10-08 13:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Agent ka naam', max_length=100)),
                ('personality_type', models.CharField(choices=[('friendly', 'Friendly & Casual'), ('professional', 'Professional & Formal'), ('persuasive', 'Sales Focused'), ('supportive', 'Customer Support'), ('custom', 'Custom Trained')], default='friendly', max_length=20)),
                ('voice_model', models.CharField(default='en-US-female-1', max_length=50)),
                ('status', models.CharField(choices=[('training', 'Initial Training'), ('learning', 'Learning from Calls'), ('active', 'Fully Active'), ('optimizing', 'Performance Optimizing'), ('paused', 'Paused')], default='training', max_length=20)),
                ('training_level', models.IntegerField(default=0, help_text='0-100 training completion')),
                ('calls_handled', models.IntegerField(default=0)),
                ('successful_conversions', models.IntegerField(default=0)),
                ('conversation_memory', models.JSONField(default=dict, help_text='Agent ki memory aur learning')),
                ('customer_preferences', models.JSONField(default=dict, help_text='Customer behavior patterns')),
                ('sales_script', models.TextField(blank=True, help_text='Dynamic sales script')),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('avg_call_duration', models.FloatField(default=0.0)),
                ('customer_satisfaction', models.FloatField(default=0.0)),
                ('working_hours_start', models.TimeField(default='09:00')),
                ('working_hours_end', models.TimeField(default='18:00')),
                ('max_daily_calls', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Agent',
                'verbose_name_plural': 'AI Agents',
                'db_table': 'ai_agents',
            },
        ),
        migrations.CreateModel(
            name='AIAgentTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('training_type', models.CharField(choices=[('script', 'Sales Script Training'), ('objections', 'Objection Handling'), ('product', 'Product Knowledge'), ('personality', 'Personality Training'), ('conversation', 'Conversation Flow')], max_length=20)),
                ('training_data', models.JSONField(help_text='Complete training content')),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='agents.aiagent')),
            ],
            options={
                'db_table': 'ai_agent_training',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('interest_level', models.CharField(choices=[('cold', 'Cold Lead'), ('warm', 'Warm Lead'), ('hot', 'Hot Lead'), ('converted', 'Converted Customer')], default='cold', max_length=20)),
                ('communication_style', models.CharField(choices=[('direct', 'Direct & Quick'), ('detailed', 'Detailed Discussion'), ('friendly', 'Casual & Friendly'), ('formal', 'Professional & Formal')], default='friendly', max_length=20)),
                ('call_preference_time', models.CharField(default='morning', help_text='Best time to call', max_length=50)),
                ('total_calls', models.IntegerField(default=0)),
                ('successful_calls', models.IntegerField(default=0)),
                ('last_interaction', models.DateTimeField(blank=True, null=True)),
                ('next_followup', models.DateTimeField(blank=True, null=True)),
                ('is_converted', models.BooleanField(default=False)),
                ('conversion_date', models.DateTimeField(blank=True, null=True)),
                ('conversion_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conversation_history', models.JSONField(default=list, help_text='Conversation patterns and responses')),
                ('objections_raised', models.JSONField(default=list, help_text='Common objections from this customer')),
                ('preferences', models.JSONField(default=dict, help_text='Customer preferences learned by AI')),
                ('is_do_not_call', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='agents.aiagent')),
            ],
            options={
                'db_table': 'customer_profiles',
                'unique_together': {('ai_agent', 'phone_number')},
            },
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('call_type', models.CharField(choices=[('inbound', 'Inbound Call'), ('outbound', 'Outbound Call'), ('callback', 'Scheduled Callback'), ('followup', 'Follow-up Call')], max_length=20)),
                ('outcome', models.CharField(choices=[('answered', 'Call Answered'), ('voicemail', 'Voicemail Left'), ('busy', 'Customer Busy'), ('interested', 'Customer Interested'), ('callback_requested', 'Callback Requested'), ('converted', 'Successfully Converted'), ('not_interested', 'Not Interested'), ('do_not_call', 'Do Not Call Request')], default='answered', max_length=30)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('conversation_transcript', models.TextField(blank=True, help_text='Full conversation text')),
                ('customer_sentiment', models.JSONField(default=dict, help_text='HumeAI sentiment analysis')),
                ('agent_performance', models.JSONField(default=dict, help_text='How well agent performed')),
                ('learning_extracted', models.JSONField(default=dict, help_text='What agent learned from this call')),
                ('followup_scheduled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('twilio_call_sid', models.CharField(blank=True, max_length=100)),
                ('hume_conversation_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='agents.aiagent')),
                ('customer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='agents.customerprofile')),
            ],
            options={
                'db_table': 'call_sessions',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledCallback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('missed', 'Missed'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('priority_level', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('reason', models.CharField(help_text='Why this callback was scheduled', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('expected_outcome', models.CharField(blank=True, max_length=100)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_outcome', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_callbacks', to='agents.aiagent')),
                ('customer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_callbacks', to='agents.customerprofile')),
            ],
            options={
                'db_table': 'scheduled_callbacks',
                'ordering': ['scheduled_datetime'],
            },
        ),
    ]
