# Generated by Django 4.2.24 on 2025-10-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_aiagent_aiagenttraining_customerprofile_callsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='business_info',
            field=models.JSONField(default=dict, help_text='Business information including company_name, company_website, company_phone, industry, business_description'),
        ),
        migrations.AddField(
            model_name='agent',
            name='compliance_settings',
            field=models.JSONField(default=dict, help_text='Compliance and security settings: call_recording, gdpr_compliant, data_retention, etc.'),
        ),
        migrations.AddField(
            model_name='agent',
            name='conversation_settings',
            field=models.JSONField(default=dict, help_text='Advanced conversation settings: max_call_duration, follow_up_enabled, objection_handling_enabled, etc.'),
        ),
        migrations.AddField(
            model_name='agent',
            name='integrations',
            field=models.JSONField(default=dict, help_text='Integration settings for CRM, calendar, email systems'),
        ),
        migrations.AddField(
            model_name='agent',
            name='knowledge_files',
            field=models.JSONField(default=dict, help_text='File paths for knowledge base: product_catalog, training_scripts, faq_document, company_brochure, competitor_analysis'),
        ),
        migrations.AddField(
            model_name='agent',
            name='learning_config',
            field=models.JSONField(default=dict, help_text='AI learning and optimization settings'),
        ),
        migrations.AddField(
            model_name='agent',
            name='performance_config',
            field=models.JSONField(default=dict, help_text='Performance targets and analytics configuration'),
        ),
        migrations.AddField(
            model_name='agent',
            name='webhook_settings',
            field=models.JSONField(default=dict, help_text='Custom webhook URLs for call events'),
        ),
    ]
