# Generated by Django 4.2.7 on 2025-10-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_business_info_agent_compliance_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='campaign_schedule',
            field=models.JSONField(blank=True, default=dict, help_text="Campaign schedule configuration: {type: 'immediate'|'scheduled', date?: 'YYYY-MM-DD', time?: 'HH:MM'}"),
        ),
        migrations.AddField(
            model_name='agent',
            name='voice_tone',
            field=models.CharField(default='friendly', help_text='Voice tone for the agent (friendly, professional, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='agent',
            name='website_url',
            field=models.URLField(blank=True, help_text='Business website URL for agent context'),
        ),
    ]
