# Generated by Django 5.2.7 on 2025-10-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agent_campaign_schedule_agent_voice_tone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='api_key_source',
            field=models.CharField(choices=[('account_default', 'Use Account Default'), ('custom', 'Custom Agent Key')], default='account_default', help_text='Whether to use account default or custom API key', max_length=20),
        ),
        migrations.AlterField(
            model_name='agent',
            name='hume_ai_api_key',
            field=models.CharField(blank=True, help_text="Custom Hume AI API key for this agent (only if api_key_source='custom')", max_length=200),
        ),
    ]
