# Generated by Django 5.2.7 on 2025-10-12 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agent_api_key_source_alter_agent_hume_ai_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsession',
            name='ai_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='agents.aiagent'),
        ),
        migrations.CreateModel(
            name='CallRoutingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_number', models.CharField(max_length=20)),
                ('routing_method', models.CharField(max_length=50)),
                ('routing_context', models.CharField(default='general', max_length=100)),
                ('routed_at', models.DateTimeField(auto_now_add=True)),
                ('call_successful', models.BooleanField(blank=True, null=True)),
                ('selected_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
            ],
            options={
                'verbose_name': 'Call Routing Record',
                'verbose_name_plural': 'Call Routing Records',
                'ordering': ['-routed_at'],
            },
        ),
    ]
