# Generated by Django 5.2.7 on 2025-10-12 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_alter_callsession_ai_agent_callroutinghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsession',
            name='customer_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='agents.customerprofile'),
        ),
    ]
