# Generated by Django 5.2.7 on 2025-10-13 21:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='outcome',
            field=models.CharField(blank=True, choices=[('answered', 'Answered'), ('voicemail', 'Voicemail'), ('busy', 'Busy'), ('no_answer', 'No Answer'), ('converted', 'Converted'), ('not_interested', 'Not Interested')], max_length=20),
        ),
        migrations.AddField(
            model_name='callsession',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CallEmotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.FloatField()),
                ('emotion', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('intensity', models.FloatField(default=0.0)),
                ('speaker', models.CharField(blank=True, choices=[('agent', 'Agent'), ('caller', 'Caller'), ('customer', 'Customer')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotions', to='calls.callsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CallTranscript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100)),
                ('speaker', models.CharField(choices=[('agent', 'Agent'), ('caller', 'Caller'), ('customer', 'Customer')], max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('confidence', models.FloatField(default=0.0)),
                ('duration', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='calls.callsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
