# Generated by Django 5.2.7 on 2025-10-17 21:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HumeAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('hume_config_id', models.CharField(help_text='HumeAI Configuration ID', max_length=255)),
                ('voice_name', models.CharField(default='ITO', help_text='Voice model name', max_length=100)),
                ('language', models.CharField(default='en', help_text='Language code', max_length=10)),
                ('system_prompt', models.TextField(default='You are a helpful sales assistant. Be friendly, professional, and helpful.', help_text="Instructions for the AI agent's behavior")),
                ('greeting_message', models.TextField(default='Hello! How can I help you today?', help_text='Initial greeting when call starts')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hume_agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HumeAI Agent',
                'verbose_name_plural': 'HumeAI Agents',
                'db_table': 'hume_agents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TwilioCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_sid', models.CharField(help_text='Twilio Call SID', max_length=255, unique=True)),
                ('from_number', models.CharField(max_length=20)),
                ('to_number', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='outbound', max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('busy', 'Busy'), ('no_answer', 'No Answer'), ('canceled', 'Canceled')], default='initiated', max_length=20)),
                ('hume_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('hume_chat_id', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.IntegerField(default=0, help_text='Call duration in seconds')),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='HumeAiTwilio.humeagent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='twilio_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Twilio Call',
                'verbose_name_plural': 'Twilio Calls',
                'db_table': 'twilio_calls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Customer'), ('assistant', 'AI Agent'), ('system', 'System')], max_length=20)),
                ('message', models.TextField()),
                ('emotion_scores', models.JSONField(blank=True, help_text='Emotion detection scores', null=True)),
                ('sentiment', models.CharField(blank=True, max_length=20, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_logs', to='HumeAiTwilio.twiliocall')),
            ],
            options={
                'verbose_name': 'Conversation Log',
                'verbose_name_plural': 'Conversation Logs',
                'db_table': 'conversation_logs',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CallAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_messages', models.IntegerField(default=0)),
                ('user_messages', models.IntegerField(default=0)),
                ('agent_messages', models.IntegerField(default=0)),
                ('overall_sentiment', models.CharField(blank=True, max_length=20, null=True)),
                ('positive_score', models.FloatField(default=0.0)),
                ('negative_score', models.FloatField(default=0.0)),
                ('neutral_score', models.FloatField(default=0.0)),
                ('top_emotions', models.JSONField(blank=True, null=True)),
                ('interruptions', models.IntegerField(default=0)),
                ('response_time_avg', models.FloatField(default=0.0, help_text='Average response time in seconds')),
                ('lead_qualified', models.BooleanField(default=False)),
                ('appointment_booked', models.BooleanField(default=False)),
                ('sale_made', models.BooleanField(default=False)),
                ('keywords_mentioned', models.JSONField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='HumeAiTwilio.twiliocall')),
            ],
            options={
                'verbose_name': 'Call Analytics',
                'verbose_name_plural': 'Call Analytics',
                'db_table': 'call_analytics',
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('twilio', 'Twilio'), ('hume', 'HumeAI')], max_length=20)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('headers', models.JSONField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='HumeAiTwilio.twiliocall')),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'verbose_name_plural': 'Webhook Logs',
                'db_table': 'webhook_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='twiliocall',
            index=models.Index(fields=['call_sid'], name='twilio_call_call_si_bb2bd1_idx'),
        ),
        migrations.AddIndex(
            model_name='twiliocall',
            index=models.Index(fields=['status'], name='twilio_call_status_15a203_idx'),
        ),
        migrations.AddIndex(
            model_name='twiliocall',
            index=models.Index(fields=['from_number'], name='twilio_call_from_nu_fb5a80_idx'),
        ),
        migrations.AddIndex(
            model_name='twiliocall',
            index=models.Index(fields=['to_number'], name='twilio_call_to_numb_b0bfca_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['source', 'event_type'], name='webhook_log_source_4c9edb_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['processed'], name='webhook_log_process_8f7aab_idx'),
        ),
    ]
