# Generated by Django 5.2.7 on 2025-10-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hume_ai_api_key',
            field=models.CharField(blank=True, help_text="Default Hume AI API key for all user's agents", max_length=200),
        ),
    ]
