# Generated by Django 4.2.7 on 2025-10-03 09:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('limit_warning', 'Limit Warning (80%)'), ('limit_exceeded', 'Limit Exceeded')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='end_date',
            new_name='current_period_end',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='start_date',
            new_name='current_period_start',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='agents_used',
            new_name='minutes_used_this_month',
        ),
        migrations.RemoveField(
            model_name='billinghistory',
            name='billing_period_end',
        ),
        migrations.RemoveField(
            model_name='billinghistory',
            name='billing_period_start',
        ),
        migrations.RemoveField(
            model_name='billinghistory',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='billinghistory',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='billinghistory',
            name='stripe_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='minutes_used',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='next_billing_date',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='ai_assistance',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='analytics',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='billing_cycle',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='inbound_calls',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_agents',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_minutes',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='outbound_calls',
        ),
        migrations.AddField(
            model_name='billinghistory',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='advanced_analytics',
            field=models.BooleanField(default=False, help_text='Advanced analytics, API access'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='agents_allowed',
            field=models.IntegerField(default=1, help_text='Number of agents allowed'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='analytics_access',
            field=models.BooleanField(default=False, help_text='Access to analytics/explainability'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='call_minutes_limit',
            field=models.IntegerField(default=1000, help_text='Monthly call minutes (inbound, outbound, or total)'),
        ),
        migrations.AlterField(
            model_name='billinghistory',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20),
        ),
        migrations.DeleteModel(
            name='UsageMetrics',
        ),
        migrations.AddField(
            model_name='usagealert',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_alerts', to='subscriptions.subscription'),
        ),
    ]
