# Generated by Django 4.2.7 on 2025-10-03 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0002_usagealert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionAddon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('addon_type', models.CharField(choices=[('minutes', 'Extra Minutes'), ('storage', 'Extra Storage'), ('agents', 'Additional Agents'), ('features', 'Premium Features')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly'), ('lifetime', 'Lifetime')], default='month', max_length=20)),
                ('extra_minutes', models.IntegerField(default=0)),
                ('extra_storage_gb', models.IntegerField(default=0)),
                ('extra_agents', models.IntegerField(default=0)),
                ('features_included', models.JSONField(default=dict)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='billinghistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['sort_order', 'price']},
        ),
        migrations.AlterModelOptions(
            name='usagealert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='billinghistory',
            name='billing_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billinghistory',
            name='billing_period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billinghistory',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='billinghistory',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billinghistory',
            name='invoice_type',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('overage', 'Overage Charges'), ('setup', 'Setup Fee'), ('addon', 'Add-on'), ('credit', 'Credit')], default='subscription', max_length=20),
        ),
        migrations.AddField(
            model_name='billinghistory',
            name='last_four',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='billinghistory',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billinghistory',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='billinghistory',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='billinghistory',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='billinghistory',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billinghistory',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='overage_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='overage_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='renewal_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='ai_agents_allowed',
            field=models.IntegerField(default=1, help_text='AI agents allowed'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='api_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='auto_campaigns',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='backup_retention_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='billing_cycle',
            field=models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly'), ('lifetime', 'Lifetime')], default='month', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='call_recording',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='call_transcription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='concurrent_calls',
            field=models.IntegerField(default=5, help_text='Concurrent calls limit'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='crm_integration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='custom_integration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_percentage',
            field=models.IntegerField(default=0, help_text='Annual discount %'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='priority_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='sentiment_analysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='setup_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='storage_gb',
            field=models.IntegerField(default=1, help_text='Storage in GB'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='webhook_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usagealert',
            name='action_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usagealert',
            name='action_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usagealert',
            name='action_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='usagealert',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usagealert',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usagealert',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usagealert',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='usagealert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usagealert',
            name='title',
            field=models.CharField(default='Alert', max_length=200),
        ),
        migrations.AlterField(
            model_name='billinghistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trialing', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('incomplete', 'Incomplete'), ('expired', 'Expired')], default='trialing', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='advanced_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='analytics_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='call_minutes_limit',
            field=models.IntegerField(default=1000, help_text='Monthly call minutes'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise'), ('custom', 'Custom Enterprise')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usagealert',
            name='alert_type',
            field=models.CharField(choices=[('limit_warning', 'Usage Warning (80%)'), ('limit_exceeded', 'Limit Exceeded'), ('payment_failed', 'Payment Failed'), ('subscription_ending', 'Subscription Ending'), ('trial_ending', 'Trial Ending'), ('overage_charges', 'Overage Charges')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserSubscriptionAddon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionaddon')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='subscriptions.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_payment_method_id', models.CharField(max_length=100)),
                ('card_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('discover', 'Discover'), ('other', 'Other')], max_length=20)),
                ('last_four', models.CharField(max_length=4)),
                ('exp_month', models.IntegerField()),
                ('exp_year', models.IntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minutes_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('agents_used', models.IntegerField(default=0)),
                ('storage_used_mb', models.IntegerField(default=0)),
                ('api_calls_made', models.IntegerField(default=0)),
                ('call_id', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('feature_used', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['subscription', 'timestamp'], name='subscriptio_subscri_5bff81_idx'), models.Index(fields=['call_id'], name='subscriptio_call_id_319ea6_idx')],
            },
        ),
    ]
