# Generated by Django 4.2.7 on 2025-10-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionaddon_alter_billinghistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='minutes_inbound_limit',
            field=models.IntegerField(default=500, help_text='Monthly inbound call minutes'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='minutes_outbound_limit',
            field=models.IntegerField(default=500, help_text='Monthly outbound call minutes'),
        ),
    ]
